package com.jmane2026.easyoregeneration.config;

import net.neoforged.neoforge.common.ModConfigSpec;

public class EasyOreGenConfig {
    public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
    public static final ModConfigSpec SPEC;

    public static final ModConfigSpec.IntValue GENERATION_SPEED;
    public static final ModConfigSpec.IntValue GENERATION_QUANTITY;

    static {
        BUILDER.push("Easy Ore Generation Config");

        GENERATION_SPEED = BUILDER
                .comment("Controls the speed of the Precise Ore Generator (in ticks)")
                .defineInRange("generationSpeed", 20, 1, 100);

        GENERATION_QUANTITY = BUILDER
                .comment("Controls how much ore is generated by the Precise Ore Generator at the configured speed.")
                .defineInRange("generationQuantity", 1, 1, 64);

        BUILDER.pop();
        SPEC = BUILDER.build();
    }
}